apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: cloud-armor-policy
spec:
  default:
    securityPolicy: gke-gtw-test-security-policy
  targetRef:
    group: ""
    kind: Service
    name: store-v1
